name: Проблема/баг в приложении
description: Если вы обнаружили проблему, этот пункт для вас
title: "[Ошибка]: "
body:
  - type: input
    id: device
    attributes:
      label: Устройство
      description: Укажи свое устройство и операционную систему
      placeholder: Например - Samsung S24 на Android 14
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Подробнее о проблеме
      description: Укажи, как вызвать эту проблему пошагово, желательно добавь скриншот или запись экрана
      placeholder: |
        Например
        1. Удалить все сохраненные расписания
        2. Перключиться на "Поиск"
        3. Вернуться на "Расписание"
        4. Все взорвется
    validations:
      required: true

  - type: checkboxes
    id: is_latest
    attributes:
      label: Я подтверждаю, что...
      options:
        - label: Использую последнюю версию приложения
          required: true
        - label: Похожей ошибки нет
          required: true